
use ${DB};
ADD JAR file://${mysql_jar};

ANALYZE TABLE date_dim COMPUTE STATISTICS;
ANALYZE TABLE time_dim COMPUTE STATISTICS;
ANALYZE TABLE item COMPUTE STATISTICS;
ANALYZE TABLE customer COMPUTE STATISTICS;
ANALYZE TABLE customer_demographics COMPUTE STATISTICS;
ANALYZE TABLE household_demographics COMPUTE STATISTICS;
ANALYZE TABLE customer_address COMPUTE STATISTICS;
ANALYZE TABLE store COMPUTE STATISTICS;
ANALYZE TABLE promotion COMPUTE STATISTICS;
ANALYZE TABLE web_site COMPUTE STATISTICS;


ANALYZE TABLE inventory partition(inv_date) COMPUTE STATISTICS;
ANALYZE TABLE store_sales partition(ss_sold_date) COMPUTE STATISTICS;
ANALYZE TABLE store_returns partition(sr_returned_date) COMPUTE STATISTICS;
ANALYZE TABLE web_sales partition(ws_sold_date) COMPUTE STATISTICS;
ANALYZE TABLE web_returns partition(wr_returned_date) COMPUTE STATISTICS;
ANALYZE TABLE catalog_sales partition(cs_sold_date) COMPUTE STATISTICS;
ANALYZE TABLE catalog_returns partition(cr_returned_date) COMPUTE STATISTICS;

ANALYZE TABLE web_page COMPUTE STATISTICS;
ANALYZE TABLE income_band COMPUTE STATISTICS;
ANALYZE TABLE call_center COMPUTE STATISTICS;
ANALYZE TABLE ship_mode COMPUTE STATISTICS;
ANALYZE TABLE reason COMPUTE STATISTICS;
ANALYZE TABLE catalog_page COMPUTE STATISTICS;
ANALYZE TABLE warehouse COMPUTE STATISTICS;
